### PR TITLE
add subdivisions to VSCode Extension Settings

### PR DESCRIPTION
**Pull request by philanderson888**
First merge request - let's see how it goes!

Related to https://github.com/rokucommunity/vscode-brightscript-language/issues/378

### CODE REVIEW

**Comment by TwitchBronBron** [comment]
Looking good so far. I noticed the code was a little out of date, so I pushed a few fixes to get it back in sync. 

Here are a few suggestions:

- [ ] Make a dedicated category for all the `.format` settings called "Formatting"

- [ ] Make a new "Project Settings" category and move these settings in there:
   - `brightscript.configFile`
   - `brightscript.bsdk`
   - `brightscript.enableLanguageServer`
 

- [ ] rename "Terminal Output" to "Debug Logging" and make sure all of these commands are in there
  - `clear console on channel start`
  - `clear on launch`
  - `focus on launch`
  - `hyperlink format`
  - `include stack traces`
  - `output panel startup behavior`

- [ ] Rename "Network And Device Discovery" to "Device Discovery". Its children can remain.

- [ ] create new category called "Device Control (ECP)" and move these settings there:
   - `remote control.host`
   - `brightscript.sendRemoteTextHistory.limit`
   - `brightscript.sendRemoteTextHistory.enabled`
   - `brightscript.remoteControlMode.enableActiveAnimation`

 -  [ ] create a new category called "Miscelaneous", move it to the bottom,  and move these settings there: 
     - `brightscript.extensionLogfilePath`

- [ ] remove all the "order" properties in favor of just listing the categories alphabetically

**Comment by philandersonaccedo** [comment]
Got you fully.  Not sure how the sync issues occurred, as did fork from your master branch on the day; never mind and thanks.  I'll be aware in the future, thanks.

**Comment by philandersonaccedo** [comment]
With your suggested changes @TwitchBronBron I will implement, looks good.

**Comment by philanderson888** [comment]
Thank you @TwitchBronBron all changes made as you requested, thanks.

**Comment by TwitchBronBron** [comment]
Everything looks great! Thanks for this.

**Comment by philanderson888** [comment]
Thanks Bron - a pleasure to help !!!

**Pull request merged**
