### PR TITLE
Feat/support bs go to alternate file

### PR DESCRIPTION
**Pull request by georgejecook**

### CODE REVIEW

**Comment by TwitchBronBron** [comment]
This looks like it depends on your other pull request, so I will hold off on reviewing it until that one is complete. Maybe try to submit your PRs without dependent changes if possible?

**Comment by georgejecook** [comment]
oh, yes indeed.

**Comment by TwitchBronBron** [comment]
@georgejecook can you resolve the merge conflict?

**Comment by georgejecook** [comment]
hey @TwitchBronBron I've merged in latest master.

**Pull request merged**
