### PR TITLE
Convert build to webpack

### PR DESCRIPTION
**Pull request by TwitchBronBron**
As per the [recommendation of the vscode extension team](https://code.visualstudio.com/api/working-with-extensions/bundling-extension), (that naggy message after every vsix build), I converted the build process to use webpack.

### CODE REVIEW

**Comment by TwitchBronBron** [comment]
@triwav, @chrisdp, @georgejecook, Could you guys pull down this PR, build it, and make sure everything works well for you? It seemed to work just fine for me...but since completely changing the build system is a pretty substantial change, i'd feel better with a few other people validating that it works properly before I merge it.

**Comment by georgejecook** [comment]
Seems to work for package, and I can build and run in vscode

get these unit test failures.

```
2 failing

  1) Debugger
       updateManifestBsConsts
         should throw error when there is no bs_const line:
     TypeError: assert.rejects is not a function
      at Object.<anonymous> (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/src/BrightScriptDebugSession.spec.ts:157:26)
      at Generator.next (<anonymous>)
      at /Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/src/BrightScriptDebugSession.spec.ts:7:71
      at new Promise (<anonymous>)
      at __awaiter (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/src/BrightScriptDebugSession.spec.ts:3:12)
      at Context.it (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/src/BrightScriptDebugSession.spec.ts:156:76)
      at callFn (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runnable.js:372:21)
      at Test.Runnable.run (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runnable.js:364:7)
      at Runner.runTest (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runner.js:455:10)
      at /Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runner.js:573:12
      at next (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runner.js:369:14)
      at /Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runner.js:379:7
      at next (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runner.js:303:14)
      at /Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runner.js:342:7
      at done (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runnable.js:319:5)
      at callFn (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runnable.js:395:7)
      at Hook.Runnable.run (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runnable.js:364:7)
      at next (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runner.js:317:10)
      at Immediate.<anonymous> (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runner.js:347:5)
      at runCallback (timers.js:763:18)
      at tryOnImmediate (timers.js:734:5)
      at processImmediate (timers.js:716:5)

  2) Debugger
       updateManifestBsConsts
         should throw error if there is consts in the bsConsts that are not in the manifest:
     TypeError: assert.rejects is not a function
      at Object.<anonymous> (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/src/BrightScriptDebugSession.spec.ts:164:26)
      at Generator.next (<anonymous>)
      at /Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/src/BrightScriptDebugSession.spec.ts:7:71
      at new Promise (<anonymous>)
      at __awaiter (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/src/BrightScriptDebugSession.spec.ts:3:12)
      at Context.it (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/src/BrightScriptDebugSession.spec.ts:162:109)
      at callFn (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runnable.js:372:21)
      at Test.Runnable.run (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runnable.js:364:7)
      at Runner.runTest (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runner.js:455:10)
      at /Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runner.js:573:12
      at next (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runner.js:369:14)
      at /Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runner.js:379:7
      at next (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runner.js:303:14)
      at /Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runner.js:342:7
      at done (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runnable.js:319:5)
      at callFn (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runnable.js:395:7)
      at Hook.Runnable.run (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runnable.js:364:7)
      at next (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runner.js:317:10)
      at Immediate.<anonymous> (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/node_modules/mocha/lib/runner.js:347:5)
      at runCallback (timers.js:763:18)
      at tryOnImmediate (timers.js:734:5)
      at processImmediate (timers.js:716:5)



npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! brightscript@1.19.5 test: `ts-mocha "src/**/*.spec.ts" --full-trace`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the brightscript@1.19.5 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/georgecook/.npm/_logs/2019-09-22T14_16_39_221Z-debug.log
Mac-mini-2:vscode-brightscript-language georgecook$```

**Comment by chrisdp** [comment]
What’s the status of this Pr? Is this moot due to our move to git workflows with v2?

**Comment by TwitchBronBron** [comment]
It's still something i'd like to do. It'll drastically reduce the the extension package size. However, I want to do more testing on it first to see if it's any slower during development. In my experience, the webpack projects I work on for my day job are usually a good bit slower, so before we make the switch I want to make sure it won't have a negative impact on our development cycle. 

It's not overly critical, so I'll get to it eventually. :D

**Review by PabloSchmidtRokuDev — APPROVED** [review]

**Comment by TwitchBronBron** [comment]
Closing in favor of #335

**Pull request closed without merging**
